// AUTO-GENERATED by @nonnajs/compiler - do not edit by hand.
import { defineDependencies } from "@nonnajs/di";
import { HttpRequestContext } from "../request-context";
import { LoggerService } from "../logger.service";
import { UserRepository } from "../user.repository";
import { UserController } from "../user.controller";
import { HttpRouter } from "../http-router";
import { SERVER_CONFIG } from "../config";
defineDependencies(HttpRequestContext, []);
defineDependencies(LoggerService, []);
defineDependencies(UserRepository, []);
defineDependencies(UserController, [
    UserRepository,
    LoggerService,
    HttpRequestContext
]);
defineDependencies(HttpRouter, [
    HttpRequestContext,
    UserController,
    SERVER_CONFIG
]);
